object frmRecebePedido: TfrmRecebePedido
  Left = 37
  Top = 148
  Width = 479
  Height = 237
  BorderIcons = [biSystemMenu]
  Caption = 'Recebimento'
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  Position = poScreenCenter
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 13
  object Label1: TLabel
    Left = 4
    Top = 3
    Width = 131
    Height = 20
    Caption = 'Tipo Pagamento'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -16
    Font.Name = 'MS Sans Serif'
    Font.Style = [fsBold]
    ParentFont = False
    Transparent = True
  end
  object Label3: TLabel
    Left = 5
    Top = 67
    Width = 153
    Height = 20
    Caption = 'Tipo Pagamento(2)'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clBlack
    Font.Height = -16
    Font.Name = 'MS Sans Serif'
    Font.Style = [fsBold]
    ParentFont = False
    Transparent = True
  end
  object cboTipoPagto: TComboBox
    Left = 5
    Top = 28
    Width = 180
    Height = 24
    BevelInner = bvSpace
    BevelKind = bkFlat
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = [fsBold]
    ItemHeight = 16
    ParentFont = False
    TabOrder = 0
  end
  object cboTPagto: TComboBox
    Left = 5
    Top = 92
    Width = 180
    Height = 24
    BevelInner = bvSpace
    BevelKind = bkFlat
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clNavy
    Font.Height = -13
    Font.Name = 'MS Sans Serif'
    Font.Style = [fsBold]
    ItemHeight = 16
    ParentFont = False
    TabOrder = 1
  end
  object lbl_edtValor: TLabeledEdit
    Left = 189
    Top = 29
    Width = 147
    Height = 35
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 89
    EditLabel.Height = 20
    EditLabel.Caption = 'Valor Pago'
    EditLabel.Font.Charset = DEFAULT_CHARSET
    EditLabel.Font.Color = clBlack
    EditLabel.Font.Height = -16
    EditLabel.Font.Name = 'MS Sans Serif'
    EditLabel.Font.Style = [fsBold]
    EditLabel.ParentFont = False
    EditLabel.Transparent = True
    Font.Charset = ANSI_CHARSET
    Font.Color = clNavy
    Font.Height = -21
    Font.Name = 'Verdana'
    Font.Style = [fsBold]
    LabelPosition = lpAbove
    LabelSpacing = 3
    ParentFont = False
    TabOrder = 2
    Text = '0,00'
  end
  object lbl_edtValorPago: TLabeledEdit
    Left = 9
    Top = 147
    Width = 147
    Height = 35
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 89
    EditLabel.Height = 20
    EditLabel.Caption = 'Valor Pago'
    EditLabel.Font.Charset = DEFAULT_CHARSET
    EditLabel.Font.Color = clBlack
    EditLabel.Font.Height = -16
    EditLabel.Font.Name = 'MS Sans Serif'
    EditLabel.Font.Style = [fsBold]
    EditLabel.ParentFont = False
    EditLabel.Transparent = True
    Font.Charset = ANSI_CHARSET
    Font.Color = clBlue
    Font.Height = -21
    Font.Name = 'Verdana'
    Font.Style = [fsBold]
    LabelPosition = lpAbove
    LabelSpacing = 3
    ParentFont = False
    TabOrder = 3
    Text = '0,00'
  end
  object lbl_edtDesconto: TLabeledEdit
    Left = 192
    Top = 91
    Width = 123
    Height = 35
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 78
    EditLabel.Height = 20
    EditLabel.Caption = 'Desconto'
    EditLabel.Font.Charset = DEFAULT_CHARSET
    EditLabel.Font.Color = clBlack
    EditLabel.Font.Height = -16
    EditLabel.Font.Name = 'MS Sans Serif'
    EditLabel.Font.Style = [fsBold]
    EditLabel.ParentFont = False
    EditLabel.Transparent = True
    Font.Charset = ANSI_CHARSET
    Font.Color = clRed
    Font.Height = -21
    Font.Name = 'Verdana'
    Font.Style = [fsBold]
    LabelPosition = lpAbove
    LabelSpacing = 3
    ParentFont = False
    TabOrder = 4
  end
  object lbl_edtAcrescimo: TLabeledEdit
    Left = 329
    Top = 93
    Width = 123
    Height = 35
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 84
    EditLabel.Height = 20
    EditLabel.Caption = 'Acr'#233'scimo'
    EditLabel.Font.Charset = DEFAULT_CHARSET
    EditLabel.Font.Color = clBlack
    EditLabel.Font.Height = -16
    EditLabel.Font.Name = 'MS Sans Serif'
    EditLabel.Font.Style = [fsBold]
    EditLabel.ParentFont = False
    EditLabel.Transparent = True
    Font.Charset = ANSI_CHARSET
    Font.Color = clBlue
    Font.Height = -21
    Font.Name = 'Verdana'
    Font.Style = [fsBold]
    LabelPosition = lpAbove
    LabelSpacing = 3
    ParentFont = False
    TabOrder = 5
  end
  object lbl_edtTotalVenda: TLabeledEdit
    Left = 192
    Top = 155
    Width = 123
    Height = 35
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 123
    EditLabel.Height = 20
    EditLabel.Caption = 'Total da Venda'
    EditLabel.Font.Charset = DEFAULT_CHARSET
    EditLabel.Font.Color = clBlack
    EditLabel.Font.Height = -16
    EditLabel.Font.Name = 'MS Sans Serif'
    EditLabel.Font.Style = [fsBold]
    EditLabel.ParentFont = False
    EditLabel.Transparent = True
    Font.Charset = ANSI_CHARSET
    Font.Color = clNavy
    Font.Height = -21
    Font.Name = 'Verdana'
    Font.Style = [fsBold]
    LabelPosition = lpAbove
    LabelSpacing = 3
    ParentFont = False
    TabOrder = 6
  end
  object lbl_edtTroco: TLabeledEdit
    Left = 329
    Top = 155
    Width = 123
    Height = 35
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 46
    EditLabel.Height = 20
    EditLabel.Caption = 'Troco'
    EditLabel.Font.Charset = DEFAULT_CHARSET
    EditLabel.Font.Color = clBlack
    EditLabel.Font.Height = -16
    EditLabel.Font.Name = 'MS Sans Serif'
    EditLabel.Font.Style = [fsBold]
    EditLabel.ParentFont = False
    EditLabel.Transparent = True
    Font.Charset = ANSI_CHARSET
    Font.Color = clRed
    Font.Height = -21
    Font.Name = 'Verdana'
    Font.Style = [fsBold]
    LabelPosition = lpAbove
    LabelSpacing = 3
    ParentFont = False
    TabOrder = 7
  end
  object lbl_edtSair: TLabeledEdit
    Left = 454
    Top = 149
    Width = 1
    Height = 21
    BevelInner = bvSpace
    BevelKind = bkFlat
    BorderStyle = bsNone
    EditLabel.Width = 3
    EditLabel.Height = 13
    EditLabel.Caption = '.'
    EditLabel.Transparent = True
    LabelPosition = lpAbove
    LabelSpacing = 3
    TabOrder = 8
  end
end
